import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/services.dart';
import 'dart:io';
import '../../models/contact_model.dart';
import '../../providers/contact_provider.dart';
import '../../widgets/animations/fade_in_slide.dart';
import 'package:country_code_picker/country_code_picker.dart';
import '../../services/storage_service.dart';
import '../../utils/error_handler.dart';
import '../../providers/user_management_provider.dart';
class AddEditContactScreen extends ConsumerStatefulWidget {
  final ContactModel? contact;

  const AddEditContactScreen({super.key, this.contact});

  @override
  ConsumerState<AddEditContactScreen> createState() => _AddEditContactScreenState();
}

class _AddEditContactScreenState extends ConsumerState<AddEditContactScreen> {
  final _formKey = GlobalKey<FormState>();
  final _storageService = StorageService();

  late String _name;
  late String _email;
  late String _phone;
  late String _company;
  late String _position;
  late String _address;
  late String _notes;
  late String _status;
  String _countryCode = '+1'; // Default
  late String _assignedTo;
  
  File? _imageFile;
  String? _avatarUrl;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _name = widget.contact?.name ?? '';
    _email = widget.contact?.email ?? '';
    _phone = widget.contact?.phone ?? '';
    _company = widget.contact?.company ?? '';
    _position = widget.contact?.position ?? '';
    _address = widget.contact?.address ?? '';
    _notes = widget.contact?.notes ?? '';
    // Prevent manual entry of leads in contact page (must use conversion)
    _status = widget.contact?.status == ContactStatus.lead ? ContactStatus.customer : (widget.contact?.status ?? ContactStatus.customer);
    _assignedTo = widget.contact?.assignedTo ?? '';
    _avatarUrl = widget.contact?.avatarUrl;
  }

  Future<void> _pickImage() async {
    final file = await _storageService.pickImage();
    if (file != null) {
      setState(() => _imageFile = file);
    }
  }

  Future<void> _submit() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      setState(() => _isLoading = true);

      try {
        String? newAvatarUrl = _avatarUrl;
        
        // Upload image if selected
        if (_imageFile != null) {
          // If new contact, we need an ID. But usually ID is generated by backend or service.
          // Here contactsProvider.addContact likely generates ID if we don't provide it, 
          // or Supabase does.
          // Wait, 'addContact' in provider calls service. addContact service usually lets DB generate ID.
          // Issue: We need ID for path 'contacts/{id}'.
          // If it's a new contact, we don't have ID yet.
          // Solution: Use a UUID generator here or upload to 'contacts/temp_{timestamp}' and ideally rename, 
          // or just use timestamp-based filename which is unique enough.
          // Let's use 'contacts/${DateTime.now().millisecondsSinceEpoch}' for new contacts.
          // For existing, use 'contacts/${widget.contact!.id}'.
          
          final pathId = widget.contact?.id ?? DateTime.now().millisecondsSinceEpoch.toString();
          final path = 'contacts/$pathId'; 
          newAvatarUrl = await _storageService.uploadAvatar(_imageFile!, path);
        }

        final contact = ContactModel(
          id: widget.contact?.id ?? '', // Service/DB will handle if empty, or we let provider handle it
          name: _name,
          email: _email,
          phone: _phone,
          company: _company,
          position: _position,
          address: _address,
          notes: _notes,
          status: _status,
          createdAt: widget.contact?.createdAt ?? DateTime.now(),
          lastContacted: widget.contact?.lastContacted ?? DateTime.now(),
          avatarUrl: newAvatarUrl,
          isFavorite: widget.contact?.isFavorite ?? false,
        );

        if (widget.contact == null) {
          await ref.read(contactsProvider.notifier).addContact(contact);
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Contact added successfully')),
            );
          }
        } else {
          await ref.read(contactsProvider.notifier).updateContact(contact);
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Contact updated successfully')),
            );
          }
        }
        if (mounted) Navigator.of(context).pop();

      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
             SnackBar(content: Text('Error: ${ErrorHandler.formatError(e)}'), backgroundColor: Colors.red),
          );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.contact == null ? 'Add Contact' : 'Edit Contact'),
        actions: [
          if (!_isLoading)
            IconButton(
              icon: const Icon(Icons.check),
              onPressed: _submit,
            ),
        ],
      ),
      body: _isLoading 
        ? const Center(child: CircularProgressIndicator())
        : Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Align(
              alignment: Alignment.topCenter,
              child: ConstrainedBox(
                constraints: const BoxConstraints(maxWidth: 600),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    // Avatar Picker
                    FadeInSlide(
                  child: Center(
                    child: Stack(
                      children: [
                        GestureDetector(
                          onTap: _pickImage,
                          child: Container(
                            padding: const EdgeInsets.all(4),
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              border: Border.all(
                                color: Theme.of(context).primaryColor,
                                width: 2,
                              ),
                            ),
                            child: CircleAvatar(
                              radius: 50,
                              backgroundColor: Theme.of(context).primaryColor,
                              backgroundImage: _imageFile != null
                                  ? FileImage(_imageFile!)
                                  : (_avatarUrl != null && _avatarUrl!.isNotEmpty)
                                      ? NetworkImage(_avatarUrl!) as ImageProvider
                                      : null,
                              child: (_imageFile == null && (_avatarUrl == null || _avatarUrl!.isEmpty))
                                  ? Text(
                                      _name.isNotEmpty
                                          ? _name.substring(0, 1).toUpperCase()
                                          : 'C',
                                      style: const TextStyle(
                                        fontSize: 40,
                                        fontWeight: FontWeight.bold,
                                        color: Colors.white,
                                      ),
                                    )
                                  : null,
                            ),
                          ),
                        ),
                        Positioned(
                          bottom: 0,
                          right: 0,
                          child: GestureDetector(
                            onTap: _pickImage,
                            child: Container(
                              padding: const EdgeInsets.all(8),
                              decoration: BoxDecoration(
                                color: Theme.of(context).primaryColor,
                                shape: BoxShape.circle,
                                border: Border.all(
                                  color: Theme.of(context).scaffoldBackgroundColor,
                                  width: 2,
                                ),
                              ),
                              child: const Icon(
                                Icons.camera_alt,
                                size: 20,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 32),

                FadeInSlide(
                  delay: 0,
                  child: TextFormField(
                    initialValue: _name,
                    decoration: const InputDecoration(
                      labelText: 'Contact Name',
                      prefixIcon: Icon(Icons.person_outline),
                      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                    ),
                    validator: (value) =>
                        value!.isEmpty ? 'Please enter a name' : null,
                    onChanged: (val) => setState(() => _name = val), // Update for avatar preview
                    onSaved: (value) => _name = value!,
                  ),
                ),
                const SizedBox(height: 16),
                FadeInSlide(
                  delay: 0.1,
                  child: TextFormField(
                    initialValue: _email,
                    decoration: const InputDecoration(
                      labelText: 'Email Address',
                      prefixIcon: Icon(Icons.email_outlined),
                      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                    ),
                    validator: (value) =>
                        value!.isEmpty ? 'Please enter an email' : null,
                    onSaved: (value) => _email = value!,
                    keyboardType: TextInputType.emailAddress,
                  ),
                ),
                const SizedBox(height: 16),
                FadeInSlide(
                  delay: 0.2,
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Row(
                      children: [
                        CountryCodePicker(
                          onChanged: (country) {
                             setState(() {
                               _countryCode = country.dialCode ?? '+1';
                             });
                          },
                          // Try to set initial selection based on existing phone or default to US
                          initialSelection: _phone.isNotEmpty ? _phone : 'US',
                          favorite: const ['+1', 'US', 'IN', 'GB'],
                          showCountryOnly: false,
                          showOnlyCountryWhenClosed: false,
                          alignLeft: false,
                        ),
                        Expanded(
                          child: TextFormField(
                            initialValue: _phone,
                            decoration: const InputDecoration(
                              hintText: 'Phone Number',
                              border: InputBorder.none,
                              counterText: "", // Hide character counter
                            ),
                            keyboardType: TextInputType.phone,
                            maxLength: 15, // Limit length to 15 digits (E.164 standard)
                            inputFormatters: [
                              FilteringTextInputFormatter.digitsOnly,
                            ],
                            validator: (value) {
                              if (value == null || value.isEmpty) return 'Enter phone number';
                              // Basic length check (min 7 digits)
                              if (value.length < 7) return 'Too short';
                              return null;
                            },
                            onSaved: (value) {
                              // If value already starts with +, assume it has code. 
                              // If not, prepend selected code.
                              if (value!.startsWith('+')) {
                                _phone = value;
                              } else {
                                _phone = '$_countryCode $value';
                              }
                            },
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                 FadeInSlide(
                   delay: 0.3,
                   child: TextFormField(
                    initialValue: _company,
                    decoration: const InputDecoration(
                      labelText: 'Company',
                      prefixIcon: Icon(Icons.business_outlined),
                      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                    ),
                    onSaved: (value) => _company = value!,
                  ),
                 ),
                const SizedBox(height: 16),
                 FadeInSlide(
                   delay: 0.4,
                   child: TextFormField(
                    initialValue: _position,
                    decoration: const InputDecoration(
                      labelText: 'Position',
                      prefixIcon: Icon(Icons.badge_outlined),
                      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                    ),
                    onSaved: (value) => _position = value!,
                  ),
                 ),
                const SizedBox(height: 16),
                 FadeInSlide(
                   delay: 0.5,
                   child: TextFormField(
                    initialValue: _address,
                    decoration: const InputDecoration(
                      labelText: 'Address',
                      prefixIcon: Icon(Icons.location_on_outlined),
                      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                    ),
                    onSaved: (value) => _address = value!,
                    onChanged: (val) => _address = val,
                    maxLines: 2,
                  ),
                 ),
                const SizedBox(height: 16),
                 FadeInSlide(
                   delay: 0.55,
                   child: Consumer(
                    builder: (context, ref, child) {
                      final usersAsync = ref.watch(userManagementProvider);
                      return usersAsync.when(
                        data: (users) {
                          final validIds = users.map((u) => u.id).toList();
                          final currentValue = validIds.contains(_assignedTo) ? _assignedTo : '';
                          return DropdownButtonFormField<String>(
                            value: currentValue.isEmpty ? null : currentValue,
                            decoration: const InputDecoration(
                              labelText: 'Assigned To',
                              prefixIcon: Icon(Icons.assignment_ind_outlined),
                              border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                            ),
                            items: [
                              const DropdownMenuItem(value: null, child: Text('Unassigned')),
                              ...users.map((user) => DropdownMenuItem(
                                value: user.id,
                                child: Text(user.name),
                              )),
                            ],
                            onChanged: (value) => setState(() => _assignedTo = value ?? ''),
                            onSaved: (value) => _assignedTo = value ?? '',
                          );
                        },
                        loading: () => const Center(child: CircularProgressIndicator()),
                        error: (_, __) => const Text('Failed to load users'),
                      );
                    },
                   ),
                 ),
                const SizedBox(height: 16),
                 FadeInSlide(
                   delay: 0.6,
                   child: DropdownButtonFormField<ContactStatus>(
                    value: _status,
                    decoration: const InputDecoration(
                      labelText: 'Status',
                      prefixIcon: Icon(Icons.flag_outlined),
                      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                      contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 16),
                    ),
                    items: ContactStatus.values
                        .where((s) => s != ContactStatus.lead)
                        .map((status) {
                      return DropdownMenuItem(
                        value: status,
                        child: Text(status.label),
                      );
                    }).toList(),
                    onChanged: (value) => setState(() => _status = value!),
                  ),
                 ),
                const SizedBox(height: 16),
                 FadeInSlide(
                   delay: 0.7,
                   child: TextFormField(
                    initialValue: _notes,
                    decoration: const InputDecoration(
                      labelText: 'Notes',
                      prefixIcon: Icon(Icons.note_alt_outlined),
                      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
                    ),
                    onSaved: (value) => _notes = value!,
                    maxLines: 3,
                  ),
                 ),
                 const SizedBox(height: 32),
                 FadeInSlide(
                   delay: 0.8,
                   child: ElevatedButton(
                     onPressed: _submit,
                     style: ElevatedButton.styleFrom(
                       padding: const EdgeInsets.symmetric(vertical: 16),
                       shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                     ),
                     child: Text(
                       widget.contact == null ? 'Create Contact' : 'Update Contact',
                       style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                     ),
                   ),
                 ),
              ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
