org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.vfs.watch=false
org.gradle.daemon=true
kotlin.daemon.jvmargs=-Xmx1024m
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

# Fix for Windows cross-drive (C: to P:) Kotlin incremental compilation failure
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
