
enum ActivityType {
  created,
  updated,
  deleted,
  commented,
  completed,
  other,
}

class ActivityModel {
  final String id;
  final String title;
  final String description;
  final DateTime date;
  final ActivityType type;
  final String? relatedEntityId;
  final String? relatedEntityType; // 'contact', 'lead', 'deal', 'task'
  final String? performedBy; // Name of person who did this
  final DateTime createdAt;

  const ActivityModel({
    required this.id,
    required this.title,
    required this.description,
    required this.date,
    required this.type,
    this.relatedEntityId,
    this.relatedEntityType,
    this.performedBy,
    required this.createdAt,
  });

  factory ActivityModel.fromJson(Map<String, dynamic> json) {
    return ActivityModel(
      id: json['id'],
      title: json['title'] ?? '',
      description: json['description'] ?? '',
      date: DateTime.parse(json['date']),
      type: ActivityType.values.firstWhere(
        (e) => e.name == (json['type'] ?? 'other'),
        orElse: () => ActivityType.other,
      ),
      relatedEntityId: json['related_entity_id'],
      relatedEntityType: json['related_entity_type'],
      performedBy: json['performed_by'],
      createdAt: DateTime.parse(json['created_at']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Usually generated by DB
      'title': title,
      'description': description,
      'date': date.toIso8601String(),
      'type': type.name,
      'related_entity_id': relatedEntityId,
      'related_entity_type': relatedEntityType,
      'performed_by': performedBy,
      'created_at': createdAt.toIso8601String(),
    };
  }
}
